apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/kt-cloudnative/springboot_crud_security
  newTag: "20240206235514"
- name: ghcr.io/ujeongeom/springboot_crud_security
  newTag: "20240215040805"
